<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table('produks')->insert([
    		[
    			'nama' => 'Nasi Putih',
		        'harga' => '10000',
		        'gambar' => 'nasiputih.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Pete',
		        'harga' => '25000',
		        'gambar' => 'nasigorengpete.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Teri',
		        'harga' => '25000',
		        'gambar' => 'nasigorengteri.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Sosis',
		        'harga' => '25000',
		        'gambar' => 'nasigorengsosis.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Spesial',
		        'harga' => '35000',
		        'gambar' => 'nasigorengspesial.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Pattaya',
		        'harga' => '35000',
		        'gambar' => 'nasigorengpattaya.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Kampung',
		        'harga' => '25000',
		        'gambar' => 'nasigorengkampung.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi Goreng Nugget',
		        'harga' => '25000',
		        'gambar' => 'nasigorengnugget.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Goreng Crispy',
		        'harga' => '30000',
		        'gambar' => 'nasiayamgorengcrispy.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Bakar',
		        'harga' => '35000',
		        'gambar' => 'nasiayambakar.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Goreng Geprek',
		        'harga' => '30000',
		        'gambar' => 'nasiayamgorenggeprek.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Bakar Cabe Hijau',
		        'harga' => '35000',
		        'gambar' => 'nasiayambakarcabehijau.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Rica Rica',
		        'harga' => '35000',
		        'gambar' => 'nasiayamricarica.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Goreng Mentega',
		        'harga' => '35000',
		        'gambar' => 'nasiayamgorengmentega.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Ayam Mozarella',
		        'harga' => '55000',
		        'gambar' => 'nasiayammozarella.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Bebek Bakar',
		        'harga' => '40000',
		        'gambar' => 'nasibebekbakar.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Bebek Goreng Geprek',
		        'harga' => '35000',
		        'gambar' => 'nasibebekgorenggeprek.jpg',
		        'deskripsi' => 'Makanan',
            ],
            [
    			'nama' => 'Nasi + Bebek Geprek Cabe Hijau',
		        'harga' => '40000',
		        'gambar' => 'nasibebekgeprekcabehijau.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mie Goreng',
		        'harga' => '25000',
		        'gambar' => 'miegoreng.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mie Goreng Seafood',
		        'harga' => '35000',
		        'gambar' => 'miegorengseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mie Kuah',
		        'harga' => '25000',
		        'gambar' => 'miekuah.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mie Kuah Seafood',
		        'harga' => '35000',
		        'gambar' => 'miekuahseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Bihun Goreng',
		        'harga' => '25000',
		        'gambar' => 'bihungoreng.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Bihun Goreng Seafood',
		        'harga' => '35000',
		        'gambar' => 'bihungorengseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Bihun Goreng Special',
		        'harga' => '35000',
		        'gambar' => 'bihungorengspecial.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Bihun Kuah',
		        'harga' => '25000',
		        'gambar' => 'bihunkuah.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Bihun Kuah Seafood',
		        'harga' => '35000',
		        'gambar' => 'bihunkuahseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ifumie Goreng',
		        'harga' => '30000',
		        'gambar' => 'ifumiegoreng.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ifumie Goreng Seafood',
		        'harga' => '35000',
		        'gambar' => 'ifumiegorengseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ifumie Goreng Special',
		        'harga' => '35000',
		        'gambar' => 'ifumiegorengspecial.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ifumie Basah',
		        'harga' => '30000',
		        'gambar' => 'ifumiebasah.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ifumie Basah Seafood',
		        'harga' => '30000',
		        'gambar' => 'ifumiebasahseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ifumie Basah Special',
		        'harga' => '30000',
		        'gambar' => 'ifumiebasahspecial.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Kwetiaw Goreng',
		        'harga' => '25000',
		        'gambar' => 'kwetiawgoreng.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Kwetiaw Goreng Seafood',
		        'harga' => '35000',
		        'gambar' => 'kwetiawgorengseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Cah Kangkung',
		        'harga' => '25000',
		        'gambar' => 'cahkangkung.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Capcay Seafood',
		        'harga' => '35000',
		        'gambar' => 'capcayseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Tumis Touge',
		        'harga' => '20000',
		        'gambar' => 'tumistouge.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Tumis Pokcoy',
		        'harga' => '25000',
		        'gambar' => 'tumispokcoy.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Tom Yam Seafood',
		        'harga' => '45000',
		        'gambar' => 'tomyamseafood.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Nila Dabu Dabu',
		        'harga' => '65000',
		        'gambar' => 'niladabudabu.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Nila Asam Manis',
		        'harga' => '65000',
		        'gambar' => 'nilaasammanis.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Nila Sambal Ijo',
		        'harga' => '60000',
		        'gambar' => 'nilasambalijo.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Nila Sauce Bangkok',
		        'harga' => '65000',
		        'gambar' => 'nilasaucebangkok.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Nila Tauco',
		        'harga' => '65000',
		        'gambar' => 'nilatauco.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Udang Asam Manis',
		        'harga' => '50000',
		        'gambar' => 'udangasammanis.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Udang Tauco',
		        'harga' => '55000',
		        'gambar' => 'udangtauco.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Udang Sauce Bangkok',
		        'harga' => '55000',
		        'gambar' => 'udangtauco.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Udang Sauce Tiram',
		        'harga' => '55000',
		        'gambar' => 'udangsaucetiram.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Cumi Asam Manis',
		        'harga' => '55000',
		        'gambar' => 'cumiasammanis.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Cumi Sauce Bangkok',
		        'harga' => '55000',
		        'gambar' => 'cumisaucebangkok.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Cumi Tauco',
		        'harga' => '55000',
		        'gambar' => 'cumitauco.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Cumi Sauce Tiram',
		        'harga' => '55000',
		        'gambar' => 'cumisaucetiram.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mix Asam Manis',
		        'harga' => '60000',
		        'gambar' => 'mixasammanis.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mix Sauce Bangkok',
		        'harga' => '60000',
		        'gambar' => 'mixsaucebangkok.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mix Sauce Tiram',
		        'harga' => '60000',
		        'gambar' => 'mixsaucetiram.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Mix Tauco',
		        'harga' => '55000',
		        'gambar' => 'mixtauco.jpg',
		        'deskripsi' => 'Makanan',
            ],
			[
    			'nama' => 'Ice Cream Tobatio',
		        'harga' => '25000',
		        'gambar' => 'icecreamtobatio.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Ice Cream Goreng Tobatio',
		        'harga' => '25000',
		        'gambar' => 'icecreamgorengtobatio.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Pisang Goreng',
		        'harga' => '15000',
		        'gambar' => 'pisanggoreng.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Pisang Goreng Keju Coklat',
		        'harga' => '25000',
		        'gambar' => 'pisanggorengkejucoklat.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Singkong Bawang Putih',
		        'harga' => '10000',
		        'gambar' => 'singkongbawangputih.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Kentang Goreng',
		        'harga' => '20000',
		        'gambar' => 'kentanggoreng.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Banana Split',
		        'harga' => '30000',
		        'gambar' => 'bananasplit.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Sosis Bakar',
		        'harga' => '25000',
		        'gambar' => 'sosisbakar.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Slice Fruit/Buah Potong',
		        'harga' => '25000',
		        'gambar' => 'slice fruit.jpg',
		        'deskripsi' => 'Snack',
            ],
			[
    			'nama' => 'Juice Sanas',
		        'harga' => '25000',
		        'gambar' => 'juicesanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Nanas',
		        'harga' => '20000',
		        'gambar' => 'juicenanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Nasir',
		        'harga' => '25000',
		        'gambar' => 'juicesanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Jeruk',
		        'harga' => '20000',
		        'gambar' => 'juicejeruk.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Jeruk Murni',
		        'harga' => '35000',
		        'gambar' => 'juicejerukmurni.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Mangga',
		        'harga' => '20000',
		        'gambar' => 'juicemangga.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Pelangi',
		        'harga' => '25000',
		        'gambar' => 'juicepelangi.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Wortel',
		        'harga' => '20000',
		        'gambar' => 'juicewortel.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Pepaya',
		        'harga' => '20000',
		        'gambar' => 'juicepepaya.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Timun',
		        'harga' => '20000',
		        'gambar' => 'juicetimun.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Buah Naga',
		        'harga' => '25000',
		        'gambar' => 'juicebuahnaga.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Terong Belanda',
		        'harga' => '20000',
		        'gambar' => 'juiceterongbelanda.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Alpukat',
		        'harga' => '20000',
		        'gambar' => 'juicealpukat.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Sirsak',
		        'harga' => '20000',
		        'gambar' => 'juicesirsak.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Kuini',
		        'harga' => '20000',
		        'gambar' => 'juicekuini.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Tomat',
		        'harga' => '20000',
		        'gambar' => 'juicetomat.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Vanesia',
		        'harga' => '25000',
		        'gambar' => 'juicevanesia.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Juice Marquisa',
		        'harga' => '25000',
		        'gambar' => 'juicemarquisa.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Kopi Hitam',
		        'harga' => '10000',
		        'gambar' => 'kopihitam.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Kopi Susu',
		        'harga' => '15000',
		        'gambar' => 'kopisusu.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Milo Panas',
		        'harga' => '20000',
		        'gambar' => 'milopanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Milo Dingin',
		        'harga' => '25000',
		        'gambar' => 'milodingin.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Teh Jahe Tobatio',
		        'harga' => '25000',
		        'gambar' => 'tehjahetobatio.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Cappucino Panas',
		        'harga' => '20000',
		        'gambar' => 'cappucinopanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Cappucino Dingin',
		        'harga' => '25000',
		        'gambar' => 'cappucinodingin.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Lemon Tea Panas',
		        'harga' => '20000',
		        'gambar' => 'lemonteapanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Lemon Tea Dingin',
		        'harga' => '25000',
		        'gambar' => 'lemonteadingin.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Teh Manis Panas',
		        'harga' => '10000',
		        'gambar' => 'tehmanispanas.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Teh Manis Dingin',
		        'harga' => '15000',
		        'gambar' => 'tehmanisdingin.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Air Mineral Botol',
		        'harga' => '5000',
		        'gambar' => 'airmineralbotol.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Teh Tawar (Panas/Dingin)',
		        'harga' => '5000',
		        'gambar' => 'tehtawar.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Bir Bintang Putih',
		        'harga' => '65000',
		        'gambar' => 'birbintangputih.jpg',
		        'deskripsi' => 'Minuman',
            ],
			[
    			'nama' => 'Bir Bintang Hitam',
		        'harga' => '60000',
		        'gambar' => 'birbintanghitam.jpg',
		        'deskripsi' => 'Minuman',
            ]
		]);
    }
}
